fix: allow setup DAO with spaces in between
stampery-labs/aragon-govern-discord-integration pull request #99
Opened 2021-06-08 17:08 UTC by gabaldon

2021-06-08 18:41 UTC, aesedepece commented on packages/bot/src/services/parseSetupMessage.ts
> +    message.content.indexOf('<@') < 0
What's `<@`?

2021-06-08 18:41 UTC, aesedepece commented on packages/bot/src/services/parseSetupMessage.ts
> +  const daoName = chunks.splice(1, rolePosition - 1).join(' ')
Is this equivalent?

```ts
// Split between the `!setup` part, the DAO name, and the allowed role
const chunks = message.replace('  ', ' ').split(/\@|!setup/)
// The allowed role is always the last chunk, so we can simply pop it
const roleAllowed = '@' + chunks.pop().trim()
// After popping the allowed role, now we can assume the DAO name is now the last chunk, let's pop it too!
const daoName = chunks.pop().trim()
```

2021-06-08 18:41 UTC, aesedepece commented on packages/bot/test/services/parseSetupMessage.spec.ts
> +})
Thanks for testing! :heart_eyes_cat:

2021-06-11 08:58 UTC, gabaldon commented on packages/bot/src/services/parseSetupMessage.ts
> +    message.content.indexOf('<@') < 0
The written role names are displayed as ids with the format <@123456>, except for @everyone, which is not a role.

2021-06-11 10:13 UTC, aesedepece requested changes

2021-06-11 10:13 UTC, aesedepece commented on packages/bot/src/services/parseSetupMessage.ts
> +  // const chunks = message.content.replace('  ', ' ').split(' ')
```suggestion
```

2021-06-11 10:13 UTC, aesedepece commented on packages/bot/src/services/parseSetupMessage.ts
> +    : message.content.replace('  ', ' ').split(/\<@|!setup/)
I think this can be simplified using the optional marker `?`after the `<` so that we can match either `@` or `<@` :
```suggestion
  const chunks = message.content.replace('  ', ' ').split(/\^?\@|!setup/)
```

2021-06-11 10:13 UTC, aesedepece commented on packages/bot/src/services/parseSetupMessage.ts
> +  const roleAllowed = '@' + chunks.pop()?.trim()
If there's a chance that roles come in the `<@whatever>` format, we may need to get rid of the `>` sign as well:
```suggestion
  const roleAllowed = '@' + chunks.pop()?.replace('>', '').trim()
```

2021-06-11 10:13 UTC, aesedepece commented on packages/bot/test/services/parseSetupMessage.spec.ts
> +})
Shall we create a test for the `<@whatever>` and `<@whatever and whatnot>` formats?

2021-06-11 11:14 UTC, gabaldon commented on packages/bot/src/services/parseSetupMessage.ts
> +  const roleAllowed = '@' + chunks.pop()?.trim()
We need to include that sign

2021-06-14 09:29 UTC, aesedepece approved these changes

2021-06-14 10:03 UTC, merged